# Site settings
title: HTML Essentials
description: "HTML Essentials for Designers. This site is designed to present my HTML 4 to designers in a clear, concise way, and provide a resource and reference for those that are new to HTML."
baseurl: "/jekyll-html-4-essentials" 
url: "http://donirby.github.io/jekyll-html-4-essentials" 
tagline: A basic guide to HTML

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title
